package golden

import com.materialkolor.dynamiccolor.MaterialDynamicColors
import com.materialkolor.scheme.Variant
import dynamiccolor.ColorSpec
import dynamiccolor.DynamicScheme
import java.io.File
import kotlin.test.Test

/**
 * Writes the golden values that `material-color-utilities` checks on every target in
 * `commonTest/.../PlatformConformanceTest.kt`. The oracle is Google's Java implementation; where the
 * JVM port already disagrees with it, the golden holds the port's value and says so, so that every
 * other target is held to the JVM port and the known divergences stay visible in one file.
 *
 * Does nothing unless `GOLDEN_OUT` names the file to write:
 *
 * ```
 * GOLDEN_OUT=$PWD/Goldens.kt ./gradlew :mcu-upstream:test --tests golden.GoldenGenerator --rerun
 * ```
 */
class GoldenGenerator {
    @Test
    fun generate() {
        val out = System.getenv("GOLDEN_OUT") ?: return
        File(out).writeText(render())
    }

    private fun render(): String =
        buildString {
            appendLine("// Generated by mcu-upstream/src/test/java/golden/GoldenGenerator.kt from the Java upstream.")
            appendLine("// Do not edit by hand.")
            appendLine("@file:Suppress(\"ktlint\")")
            appendLine()
            appendLine("package com.materialkolor")
            appendLine()
            appendLine("import com.materialkolor.scheme.Variant")
            appendLine()
            appendLine("internal object Goldens {")

            appendLine("    /** argb, hue, chroma, tone */")
            appendLine("    val hctFromArgb: List<HctGolden> = listOf(")
            for (argb in GoldenInputs.argbs) {
                val hct = hct.Hct.fromInt(argb)
                appendLine("        HctGolden(${hex(argb)}, ${hct.hue}, ${hct.chroma}, ${hct.tone}),")
            }
            appendLine("    )")
            appendLine()

            appendLine("    /** hue, chroma, tone -> solved argb */")
            appendLine("    val hctSolved: List<HctSolveGolden> = listOf(")
            for ((h, c, t) in GoldenInputs.hctGrid) {
                appendLine("        HctSolveGolden($h, $c, $t, ${hex(hct.Hct.from(h, c, t).toInt())}),")
            }
            appendLine("    )")
            appendLine()

            appendLine("    /**")
            appendLine(
                "     * FNV-1a over the argb of every MaterialDynamicColors.allDynamicColors() entry, in order, as the",
            )
            appendLine(
                "     * JVM port computes it; `matchesUpstream = false` marks where the port already differs from Java.",
            )
            appendLine("     */")
            appendLine("    val schemes: List<SchemeGolden> = listOf(")
            val names = kotlinColors.map { it.name }
            for (seed in GoldenInputs.seeds) {
                for (variant in Variant.entries) {
                    for (spec in GoldenInputs.specs) {
                        for (dark in listOf(false, true)) {
                            for (contrast in GoldenInputs.contrasts) {
                                val scheme = javaScheme(seed, variant, dark, contrast, spec)
                                val upstream = digest(names.map { javaColors.getValue(it).getArgb(scheme) })
                                val port = kotlinScheme(seed, variant, dark, contrast, spec).let { kotlin ->
                                    digest(kotlinColors.map { it.getArgb(kotlin) })
                                }
                                appendLine(
                                    "        SchemeGolden(${hex(
                                        seed,
                                    )}, Variant.$variant, \"$spec\", $dark, $contrast, " +
                                        "${hex(port)}, matchesUpstream = ${port == upstream}),",
                                )
                            }
                        }
                    }
                }
            }
            appendLine("    )")
            appendLine()

            appendLine("    val harmonized: List<Triple<Int, Int, Int>> = listOf(")
            for (design in GoldenInputs.argbs) {
                for (source in GoldenInputs.seeds) {
                    appendLine(
                        "        Triple(${hex(
                            design,
                        )}, ${hex(source)}, ${hex(blend.Blend.harmonize(design, source))}),",
                    )
                }
            }
            appendLine("    )")
            appendLine()

            appendLine("    /** seed -> complement argb followed by the five analogous colors */")
            appendLine("    val temperature: Map<Int, List<Int>> = mapOf(")
            for (seed in GoldenInputs.seeds) {
                val cache = temperature.TemperatureCache(hct.Hct.fromInt(seed))
                val colors = listOf(cache.complement.toInt()) + cache.analogousColors.map { it.toInt() }
                appendLine("        ${hex(seed)} to listOf(${colors.joinToString { hex(it) }}),")
            }
            appendLine("    )")
            appendLine()

            // QuantizerWsmeans seeds kotlin.random.Random where upstream seeds java.util.Random, so the
            // port picks different starting clusters by design; the port on the JVM is the reference.
            val quantized = com.materialkolor.quantize.QuantizerCelebi
                .quantize(GoldenInputs.image(), 128)
            val scored = com.materialkolor.score.Score
                .score(quantized)
            val upstreamScored = score.Score.score(quantize.QuantizerCelebi.quantize(GoldenInputs.image(), 128))
            appendLine("    /** Score.score(QuantizerCelebi.quantize(GoldenInputs.image(), 128)) from the JVM port */")
            appendLine("    val scored: List<Int> = listOf(${scored.joinToString { hex(it) }})")
            appendLine("    const val scoredMatchesUpstream: Boolean = ${scored == upstreamScored}")
            appendLine("}")
        }

    private val kotlinColors = MaterialDynamicColors().allDynamicColors().map { it() }

    private fun kotlinScheme(
        seed: Int,
        variant: Variant,
        dark: Boolean,
        contrast: Double,
        spec: String,
    ): com.materialkolor.scheme.DynamicScheme {
        val hct = com.materialkolor.hct.Hct
            .fromInt(seed)
        val version = com.materialkolor.dynamiccolor.ColorSpec.SpecVersion
            .valueOf(spec)
        val platform = com.materialkolor.scheme.DynamicScheme.Platform.PHONE
        return when (variant) {
            Variant.MONOCHROME -> com.materialkolor.scheme.SchemeMonochrome(hct, dark, contrast, version, platform)
            Variant.NEUTRAL -> com.materialkolor.scheme.SchemeNeutral(hct, dark, contrast, version, platform)
            Variant.TONAL_SPOT -> com.materialkolor.scheme.SchemeTonalSpot(hct, dark, contrast, version, platform)
            Variant.VIBRANT -> com.materialkolor.scheme.SchemeVibrant(hct, dark, contrast, version, platform)
            Variant.EXPRESSIVE -> com.materialkolor.scheme.SchemeExpressive(hct, dark, contrast, version, platform)
            Variant.FIDELITY -> com.materialkolor.scheme.SchemeFidelity(hct, dark, contrast, version, platform)
            Variant.CONTENT -> com.materialkolor.scheme.SchemeContent(hct, dark, contrast, version, platform)
            Variant.RAINBOW -> com.materialkolor.scheme.SchemeRainbow(hct, dark, contrast, version, platform)
            Variant.FRUIT_SALAD -> com.materialkolor.scheme.SchemeFruitSalad(hct, dark, contrast, version, platform)
        }
    }

    private val javaColors: Map<String, dynamiccolor.DynamicColor> =
        dynamiccolor
            .MaterialDynamicColors()
            .allDynamicColors()
            .map { it.get() }
            .associateBy { it.name }

    private fun javaScheme(
        seed: Int,
        variant: Variant,
        dark: Boolean,
        contrast: Double,
        spec: String,
    ): DynamicScheme {
        val hct = hct.Hct.fromInt(seed)
        val version = ColorSpec.SpecVersion.valueOf(spec)
        val platform = DynamicScheme.Platform.PHONE
        return when (variant) {
            Variant.MONOCHROME -> scheme.SchemeMonochrome(hct, dark, contrast, version, platform)
            Variant.NEUTRAL -> scheme.SchemeNeutral(hct, dark, contrast, version, platform)
            Variant.TONAL_SPOT -> scheme.SchemeTonalSpot(hct, dark, contrast, version, platform)
            Variant.VIBRANT -> scheme.SchemeVibrant(hct, dark, contrast, version, platform)
            Variant.EXPRESSIVE -> scheme.SchemeExpressive(hct, dark, contrast, version, platform)
            Variant.FIDELITY -> scheme.SchemeFidelity(hct, dark, contrast, version, platform)
            Variant.CONTENT -> scheme.SchemeContent(hct, dark, contrast, version, platform)
            Variant.RAINBOW -> scheme.SchemeRainbow(hct, dark, contrast, version, platform)
            Variant.FRUIT_SALAD -> scheme.SchemeFruitSalad(hct, dark, contrast, version, platform)
        }
    }

    private fun hex(value: Int): String = "0x%08X.toInt()".format(value)
}

/** [image] is kept byte-for-byte in step with `GoldenInputs.image()` in material-color-utilities' commonTest. */
internal object GoldenInputs {
    val argbs =
        intArrayOf(
            0xFF000000.toInt(),
            0xFFFFFFFF.toInt(),
            0xFF4285F4.toInt(),
            0xFFB3261E.toInt(),
            0xFF00FF00.toInt(),
            0xFF6750A4.toInt(),
            0xFF808080.toInt(),
            0xFFFFE082.toInt(),
        )

    val seeds =
        intArrayOf(
            0xFF4285F4.toInt(),
            0xFFB3261E.toInt(),
            0xFF808080.toInt(),
        )

    val specs = listOf("SPEC_2021", "SPEC_2025")

    val contrasts = listOf(-1.0, 0.0, 0.5, 1.0)

    val hctGrid: List<Triple<Double, Double, Double>> =
        buildList {
            for (h in listOf(0.0, 27.5, 90.0, 180.0, 282.0, 359.9)) {
                for (c in listOf(0.0, 16.0, 48.0, 120.0)) {
                    for (t in listOf(0.0, 5.0, 50.0, 87.3, 100.0)) add(Triple(h, c, t))
                }
            }
        }

    fun image(): IntArray =
        IntArray(64 * 64) { i ->
            when {
                i < 1200 -> {
                    0xFF4285F4.toInt()
                }
                i < 1900 -> {
                    0xFFB3261E.toInt()
                }
                i < 2300 -> {
                    0xFFFFE082.toInt()
                }
                else -> {
                    val r = (i * 37) and 0xFF
                    val g = ((i * 101) shr 3) and 0xFF
                    val b = (i * 13 + 7 * (i shr 6)) and 0xFF
                    (0xFF shl 24) or (r shl 16) or (g shl 8) or b
                }
            }
        }
}

internal fun digest(colors: List<Int>): Int {
    var hash = 0x811C9DC5.toInt()
    for (color in colors) {
        for (shift in intArrayOf(24, 16, 8, 0)) {
            hash = hash xor ((color shr shift) and 0xFF)
            hash *= 0x01000193
        }
    }
    return hash
}
